version: "3.8"

services:
  online_shop:
    build:
      context: .
    container_name: online_shop
    networks:
      - online_shop
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 5s

networks:
  online_shop:
    

      
